import { Order, ServiceTicket, QuoteRequest, Testimonial } from '../types';

/**
 * Production initial state: Empty arrays.
 * Real orders, service tickets, and quote requests are generated by customer transactions
 * and persisted in Firestore with local storage synchronization.
 */
export const mockOrders: Order[] = [];

export const mockServiceTickets: ServiceTicket[] = [];

export const mockQuoteRequests: QuoteRequest[] = [];

export const mockTestimonials: Testimonial[] = [
  {
    id: 't-1',
    name: 'Josephine Kimaro',
    role: 'Mkurugenzi Mtendaji',
    organization: 'Kimaro Logistics Ltd',
    rating: 5,
    comment: 'TK Stationery walichapa vitabu vyetu vya ankara, fomu na risiti kwa haraka na kiwango cha juu sana. Huduma yao ya uwasilishaji Dar es Salaam ni ya kuaminika.',
    serviceUsed: 'Huduma ya Uchapishaji & Vifaa vya Ofisi',
    isDemo: false
  },
  {
    id: 't-2',
    name: 'Dr. Michael S. Mremi',
    role: 'Mhadhiri Mwandamizi',
    organization: 'Chuo Kikuu Dar es Salaam',
    rating: 5,
    comment: 'Kila mara idara yetu inapohitaji vitini vya mitihani, ripoti zilizofungwa kwa hardcover au karatasi za ream, TK Stationery wanatoa ubora wa hali ya juu bila makosa.',
    serviceUsed: 'Uchapishaji na Hardcover Binding',
    isDemo: false
  },
  {
    id: 't-3',
    name: 'Aisha J. Mussa',
    role: 'Mfanyabiashara',
    organization: 'Mteja wa Huduma za TRA & NIDA',
    rating: 5,
    comment: 'Nilipata msaada mkubwa sana wa kutengenezewa TIN yangu ya biashara na kusajili maombi kwenye Ajira Portal. Wafanyakazi wao wana uelewa mkubwa na subira.',
    serviceUsed: 'Huduma za Serikali Mtandaoni',
    isDemo: false
  }
];
